name: HeadGetter
author: Weefle
version: 1.8
description: Get player's head easily!
main: fr.weefle.headgetter.Main
commands:
  gethead:
    description: Main command to get player's head
    permission: gethead.use